spring:
  application:
    name: zipjung-backend
  profiles:
    include: secrets
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost # no auth여도 localhost는 포함시켜줘야함
      port: 6379
  cache:
    jcache:
      config: ehcache.xml
  jackson:
    time-zone: UTC

server:
  port: 8080

# log
logging:
  level:
    org:
      springframework: info

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}